version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "03:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: eslint
    versions:
    - 7.21.0
  - dependency-name: ember-cli
    versions:
    - 3.23.0
    - 3.24.0
    - 3.25.0
  - dependency-name: ember-source
    versions:
    - 3.24.0
    - 3.24.1
    - 3.25.1
  - dependency-name: ember-cli-htmlbars
    versions:
    - 5.6.2
  - dependency-name: eslint-plugin-ember
    versions:
    - 10.1.1
    - 10.2.0
